### PR TITLE
feat: add dns config

### PR DESCRIPTION
**Pull request by alexdanger**
# Description

Added dns package building 
Fixes # (issue) https://github.com/Arriven/db1000n/issues/49

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Test Configuration

- Release version:
- Platform:

## Logs

```text
logs
```

## Screenshots

- [ ] No screenshot

### CODE REVIEW

**Comment by alexdanger** [comment]
@Arriven could you please check is there right start?

**Review by Arriven — DISMISSED** [review]

**Comment by Arriven** [comment]
@alexdanger looks good but you need to fix the linter
You can also add automatic check for correct serialization/deserialization similar to the one being present in serialize_test.go but that's optional for now

**Comment by alexdanger** [comment]
> @alexdanger looks good but you need to fix the linter You can also add automatic check for correct serialization/deserialization similar to the one being present in serialize_test.go but that's optional for now

I run golangci-lint run on my machine, it looks good.

i will open another MR with test multi configs  in the serialize_test.go

**Comment by alexdanger** [comment]
sorrl, somehow golang-lint didn't catch .golangci.yml, linter is fixed.

**Review by Arriven — APPROVED** [review]

**Pull request merged**
