### PR TITLE
Add supervisor for app restart after crash

### LINKED ISSUE #123: [improvement] [win] BAT file with supervisor/guardian
To prevent windows crash add simple supervisor in .bat file. Add .bat file to .zip package. 
For example:
```
echo starting
:start
start /w db1000n.exe
echo restarting
goto start
```

### PR DESCRIPTION
**Pull request by 5har0varik**
closes #123

### CODE REVIEW

**Comment by Arriven** [comment]
@Devaniti can you take a quick look? it looks ok to me but I'd rather check with you until I get enough time to get fluent in that script

**Comment by Devaniti** [comment]
On windows ctrl-c seems to generate non 0 exit code
You can take a look at go code to make it return 0 in that case, and I'll write supervisor in that script in the meantime

**Comment by Devaniti** [comment]
Oh wait, Ctrl+C stops whole batch script, so supervisor will not deadlock even if exit code is wrong

**Comment by Devaniti** [comment]
I made another pull request, same idea, but with comments, without using start command (I guess it's my personal preference), and with graceful exit from script when app does graceful exit
https://github.com/Arriven/db1000n/pull/141
Thanks @5har0varik for the idea!

**Pull request closed without merging**
